### ISSUE TITLE
RunSCVELO  Error in py_call_impl(callable, call_args$unnamed, call_args$named)

### ISSUE THREAD

**Issue by Githubxsw** [zhanghao-njmu/SCP#157]
Normal_Epi  <- RunSCVELO(srt = Normal_Epi , group_by = "Anno2", linear_reduction = "pca", nonlinear_reduction = "umap", mode = "stochastic", return_seurat = TRUE)
Assay 'integrated' is in the srt object but not converted.
'misc' slot is not converted.
'tools' slot is not converted.
Renamed 'umap' to convention 'X_umap' (adata.obsm).
'spliced' data must be provided.
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  SystemExit: None
Run `reticulate::py_last_error()` for details.

reticulate::py_last_error()
── Python Exception Message 
Traceback (most recent call last):
  File "/gpfs/share/home/2211110320/98Software/miniconda3/envs/R/envs/scpenv/lib/R/library/SCP/python/SCP_analysis.py", line 66, in SCVELO
    exit()
  File "/gpfs/share/home/2211110320/98Software/miniconda3/envs/R/envs/SCP_env/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

── R Traceback 
    ▆
 1. └─SCP::RunSCVELO(...)
 2.   ├─base::do.call(SCP_analysis$SCVELO, args)
 3.   └─reticulate (local) `<python.builtin.function>`(...)
 4.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
 
How I can solve this error. Thank you.

**Comment by zhanghao-njmu** [comment]
The estimation of cell velocity requires the presence of "spliced" and "unspliced" assays in your Seurat object. These matrices can be generated using [velocyto](http://velocyto.org/velocyto.py/index.html), [bustools](https://bustools.github.io/BUS_notebooks_R/velocity.html), or [alevin](https://combine-lab.github.io/alevin-fry-tutorials/2021/alevin-fry-velocity/)

**Comment by realzehuali** [comment]
Same issue.  Using data("pancreas_sub") also failed in the same way.

**Comment by realzehuali** [comment]
> data("pancreas_sub")
> pancreas_sub <- RunSCVELO(
+   srt = pancreas_sub, group_by = "SubCellType",
+   linear_reduction = "PCA", nonlinear_reduction = "UMAP"
+ )
'misc' slot is not converted.
'tools' slot is not converted.
Filtered out 12123 genes that are detected 30 counts (shared).
Normalized count data: X, spliced, unspliced.
Logarithmized X.
computing neighbors
    finished (0:00:07) --> added 
    'distances' and 'connectivities', weighted adjacency matrices (adata.obsp)
computing moments based on connectivities
    finished (0:00:00) --> added 
    'Ms' and 'Mu', moments of un/spliced abundances (adata.layers)
computing velocities
    finished (0:00:00) --> added 
    'stochastic', velocity vectors for each individual cell (adata.layers)
computing velocity graph (using 1/16 cores)
  0%|          | 0/1000 [00:00<?, ?cells/s]
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 4) + inhomogeneous part.
Run `reticulate::py_last_error()` for details.

**Comment by Georgewwek** [comment]
Hey, I hope this helps. The issue is not caused by the SCP package itself. You need to make sure that you have pandas==1.1.5 and numpy==1.21.1 installed.（py_install("pandas==1.1.5") and py_install("numpy==1.21.1")）

**Comment by yfkaajrizt92** [comment]
> Hey, I hope this helps. The issue is not caused by the SCP package itself. You need to make sure that you have pandas==1.1.5 and numpy==1.21.1 installed.（py_install("pandas==1.1.5") and py_install("numpy==1.21.1")）

Thank you for your help. However, it did not work. I met the same issue with the "pancreas_sub" data.
