### ISSUE TITLE
Error in py_module_import(module, convert = convert) :   NameError: name 'base_events' is not defined

### ISSUE THREAD

**Issue by zoan128** [zhanghao-njmu/SCP#172]
### I encoutered an error when I do "ref_data <- srt_to_adata(ref)" and "ref" is a seuratobject.
**My  code ：
#prepare
if (!require("devtools", quietly = TRUE)) {  install.packages("devtools") }
devtools::install_github("zhanghao-njmu/SCP")
SCP::PrepareEnv()
library(SCP)

#convert
ref <- readRDS("E:/ewdata/CRJdataanalysis/analysis/Chai_ref.rds")

ref_data <- srt_to_adata(ref)**
    

    Error in py_module_import(module, convert = convert) : NameError: name 'base_events' is not defined Run `reticulate::py_last_error()` for details.

### Reticulate::py_last_error() shows：

── Python Exception Message ─────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\scanpy\__init__.py", line 14, in <module>
    from . import tools as tl
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\scanpy\tools\__init__.py", line 1, in <module>
    from ..preprocessing import pca
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\scanpy\preprocessing\__init__.py", line 1, in <module>
    from ._recipes import recipe_zheng17, recipe_weinreb17, recipe_seurat
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\scanpy\preprocessing\_recipes.py", line 12, in <module>
    from ._normalization import normalize_total
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\scanpy\preprocessing\_normalization.py", line 7, in <module>
    from sklearn.utils import sparsefuncs
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\sklearn\base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\sklearn\utils\__init__.py", line 29, in <module>
    from .fixes import parse_version, threadpool_info
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\sklearn\utils\fixes.py", line 19, in <module>
    import scipy.stats
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\scipy\stats\__init__.py", line 485, in <module>
    from ._stats_py import *
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\scipy\stats\_stats_py.py", line 37, in <module>
    from numpy.testing import suppress_warnings
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\site-packages\numpy\testing\__init__.py", line 8, in <module>
    from unittest import TestCase
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\unittest\__init__.py", line 60, in <module>
    from .async_case import IsolatedAsyncioTestCase
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\unittest\async_case.py", line 1, in <module>
    import asyncio
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "E:\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "C:\Users\Lenovo\AppData\Local\R-MINI~1\envs\SCP_env\lib\asyncio\__init__.py", line 26, in <module>
    __all__ = (base_events.__all__ +
NameError: name 'base_events' is not defined

── R Traceback ──────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─SCP::srt_to_adata(ref)
 2.   └─reticulate::import("scanpy", convert = FALSE)
 3.     └─reticulate:::py_module_import(module, convert = convert)

**Comment by ZHOUDI0929** [comment]
pak::pak("rstudio/reticulate")

This problem caused by "reticulate".
You can use pak update reticulate, and this issue should be solved.

As someone who doesn’t know python at all, python environment configuration took me a whole day. Fortunately, python and R are similar, otherwise I wouldn’t know how to solve those errors.

**Comment by zhanghao-njmu** [comment]
This issue is caused by reticulate. You need to install the development version of reticulate.
https://community.rstudio.com/t/problem-with-tensorflow-2-10-and-rstudio/173917/4
