### ISSUE TITLE
problem RunPAGA

### ISSUE THREAD

**Issue by JoelHaas** [zhanghao-njmu/SCP#225]
Hi, thanks for the great package! I am trying to run trajectory inference with the PAGA wrapper and a seurat object as described in the vignette. 
when I run with my object, I get the error: 
> final_DC_multiK<-RunPAGA_1(srt=final_DC_multiK,group_by="final_labels", linear_reduction="PCA",nonlinear_reduction="UMAP")
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ValueError: Data must be 1-dimensional
Run `reticulate::py_last_error()` for details.
In addition: Warning message:
In asMethod(object) :
  sparse->dense coercion: allocating vector of size 6.3 GiB
with traceback:
── Python Exception Message ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/jhaas/.local/share/r-miniconda/envs/SCP_env/lib/python3.8/site-packages/pandas/core/frame.py", line 1593, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "/home/jhaas/.local/share/r-miniconda/envs/SCP_env/lib/python3.8/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/jhaas/.local/share/r-miniconda/envs/SCP_env/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "/home/jhaas/.local/share/r-miniconda/envs/SCP_env/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 124, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/home/jhaas/.local/share/r-miniconda/envs/SCP_env/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 589, in _homogenize
    val = sanitize_array(
  File "/home/jhaas/.local/share/r-miniconda/envs/SCP_env/lib/python3.8/site-packages/pandas/core/construction.py", line 576, in sanitize_array
    subarr = _sanitize_ndim(subarr, data, dtype, index, allow_2d=allow_2d)
  File "/home/jhaas/.local/share/r-miniconda/envs/SCP_env/lib/python3.8/site-packages/pandas/core/construction.py", line 627, in _sanitize_ndim
    raise ValueError("Data must be 1-dimensional")
ValueError: Data must be 1-dimensional

I also get an error (a different one) with the pancreas_sub (a different one): 
pancreas_sub <- RunPAGA(
+     srt = pancreas_sub, group_by = "SubCellType",
+     linear_reduction = "PCA", nonlinear_reduction = "UMAP"
+ )
'misc' slot is not converted.
'tools' slot is not converted.
Error in slot(object = object, name = "features")[[layer]] <- features : 
  more elements supplied than there are to replace

Any suggestions?

**Comment by Byronxy** [comment]
Hi, I have the same issue when run:
```
pancreas_sub <- RunSCVELO(
+   srt = pancreas_sub, group_by = "SubCellType",
+   linear_reduction = "PCA", nonlinear_reduction = "UMAP"
+ )
```
The error is:
```
Error in slot(object = object, name = "features")[[layer]] <- features : 
  more elements supplied than there are to replace
```
Does any one have any suggestions?

**Comment by chjzju** [comment]
I also have the same issue.

The error is ：
'misc' slot is not converted.
'tools' slot is not converted.
Error in slot(object = object, name = "features")[[layer]] <- features : 
 more elements supplied than there are to replace


How to solve this problem？

**Comment by zccovo** [comment]
I also have the same issue.  How to solve this problem？
