### ISSUE TITLE
An Error occurs when using SCP::PrepareVirtualEnv function

### ISSUE THREAD

**Issue by hjh-air-cond** [zhanghao-njmu/SCP#43]
Hi!

I'm recently trying your package SCP, it's really good and useful!

But when I try to install the SCP virtualenv by using SCP::PrepareVirtualEnv function, an error occurs:

```
======================== SCP python config ========================
python:         /home/jinhang/.virtualenvs/SCP/bin/python
libpython:      /home/jinhang/.pyenv/versions/3.8.8/lib/libpython3.8.so
pythonhome:     /home/jinhang/.virtualenvs/SCP:/home/jinhang/.virtualenvs/SCP
version:        3.8.8 (default, Dec 13 2022, 00:50:51)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
numpy:          /home/jinhang/.virtualenvs/SCP/lib/python3.8/site-packages/numpy
numpy_version:  1.21.6

NOTE: Python version was forced by RETICULATE_PYTHON
===================================================================
ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imp), please try reinstalling.
Error in value[[3L]](cond) :
  Failed to run 'import scanpy'. Please check manually.
```

Also, when I try to reinstall scipy in the virtualenv, that error remains:
![图片](https://user-images.githubusercontent.com/90448222/207136364-b764b270-47ec-410e-b384-b9c2df5b66b3.png)

I didn't know what brings up that error actually. Is there any soultion to this error? 

Thanks!

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/jinhang/miniconda3/envs/R4.2/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.26    RcppParallel_5.1.5 SCP_0.2.4         

loaded via a namespace (and not attached):
  [1] rappdirs_0.3.3              rtracklayer_1.58.0         
  [3] pbdZMQ_0.3-8                scattermore_0.8            
  [5] intrinsicDimension_1.2.0    princurve_2.1.6            
  [7] R.methodsS3_1.8.2           SeuratObject_4.1.3         
  [9] tidyr_1.2.1                 ggplot2_3.4.0              
 [11] bit64_4.0.5                 irlba_2.3.5.1              
 [13] DelayedArray_0.24.0         R.utils_2.12.2             
 [15] data.table_1.14.6           TrajectoryUtils_1.6.0      
 [17] KEGGREST_1.38.0             RCurl_1.98-1.9             
 [19] doParallel_1.0.17           generics_0.1.3             
 [21] BiocGenerics_0.44.0         ScaledMatrix_1.6.0         
 [23] cowplot_1.1.1               RSQLite_2.2.19             
 [25] RANN_2.6.1                  proxy_0.4-27               
 [27] future_1.29.0               bit_4.0.5                  
 [29] spatstat.data_3.0-0         xml2_1.3.3                 
 [31] httpuv_1.6.6                SummarizedExperiment_1.28.0
 [33] assertthat_0.2.1            viridis_0.6.2              
 [35] hms_1.1.2                   evaluate_0.18              
 [37] promises_1.2.0.1            fansi_1.0.3                
 [39] restfulr_0.0.15             progress_1.2.2             
 [41] dbplyr_2.2.1                igraph_1.3.5               
 [43] DBI_1.1.3                   htmlwidgets_1.5.4          
 [45] spatstat.geom_3.0-3         stats4_4.2.1               
 [47] purrr_0.3.5                 ellipsis_0.3.2             
 [49] crosstalk_1.2.0             dplyr_1.0.10               
 [51] ggnewscale_0.4.8            biomaRt_2.54.0             
 [53] deldir_1.0-6                sparseMatrixStats_1.10.0   
 [55] MatrixGenerics_1.10.0       vctrs_0.5.1                
 [57] SingleCellExperiment_1.20.0 Biobase_2.58.0             
 [59] here_1.0.1                  Cairo_1.6-0                
 [61] ROCR_1.0-11                 abind_1.4-5                
 [63] cachem_1.0.6                withr_2.5.0                
 [65] progressr_0.11.0            sctransform_0.3.5          
 [67] GenomicAlignments_1.34.0    prettyunits_1.1.1          
 [69] scran_1.26.0                goftest_1.2-3              
 [71] cluster_2.1.4               IRdisplay_1.1              
 [73] lazyeval_0.2.2              crayon_1.5.2               
 [75] spatstat.explore_3.0-5      edgeR_3.40.0               
 [77] pkgconfig_2.0.3             labeling_0.4.2             
 [79] units_0.8-1                 GenomeInfoDb_1.34.4        
 [81] nlme_3.1-160                vipor_0.4.5                
 [83] rlang_1.0.6                 globals_0.16.2             
 [85] lifecycle_1.0.3             miniUI_0.1.1.1             
 [87] filelock_1.0.2              BiocFileCache_2.6.0        
 [89] rsvd_1.0.5                  rprojroot_2.0.3            
 [91] polyclip_1.10-4             matrixStats_0.63.0         
 [93] lmtest_0.9-40               Matrix_1.5-3               
 [95] IRkernel_1.3.1.9000         zoo_1.8-11                 
 [97] base64enc_0.1-3             beeswarm_0.4.0             
 [99] ggridges_0.5.4              GlobalOptions_0.1.2        
[101] png_0.1-8                   viridisLite_0.4.1          
[103] rjson_0.2.21                bitops_1.0-7               
[105] R.oo_1.25.0                 KernSmooth_2.23-20         
[107] Biostrings_2.66.0           blob_1.2.3                 
[109] DelayedMatrixStats_1.20.0   shape_1.4.6                
[111] classInt_0.4-8              stringr_1.5.0              
[113] slingshot_2.6.0             parallelly_1.32.1          
[115] spatstat.random_3.0-1       R.cache_0.16.0             
[117] S4Vectors_0.36.1            beachmat_2.14.0            
[119] scales_1.2.1                memoise_2.0.1              
[121] magrittr_2.0.3              plyr_1.8.8                 
[123] ica_1.0-3                   zlibbioc_1.44.0            
[125] compiler_4.2.1              dqrng_0.3.0                
[127] BiocIO_1.8.0                RColorBrewer_1.1-3         
[129] clue_0.3-63                 fitdistrplus_1.1-8         
[131] Rsamtools_2.14.0            cli_3.4.1                  
[133] XVector_0.38.0              listenv_0.8.0              
[135] patchwork_1.1.2             pbapply_1.6-0              
[137] MASS_7.3-58.1               tidyselect_1.2.0           
[139] ggupset_0.3.0               stringi_1.7.8              
[141] yaml_2.3.6                  locfit_1.5-9.6             
[143] BiocSingular_1.14.0         ggrepel_0.9.2              
[145] grid_4.2.1                  tools_4.2.1                
[147] future.apply_1.10.0         parallel_4.2.1             
[149] parallelDist_0.2.6          circlize_0.4.15            
[151] uuid_1.1-0                  bluster_1.8.0              
[153] foreach_1.5.2               yaImpute_1.0-33            
[155] metapod_1.6.0               gridExtra_2.3              
[157] farver_2.1.1                Rtsne_0.16                 
[159] proxyC_0.3.3                BiocManager_1.30.19        
[161] digest_0.6.31               shiny_1.7.3                
[163] Rcpp_1.0.9                  GenomicRanges_1.50.1       
[165] scuttle_1.8.1               harmony_0.1.1              
[167] later_1.3.0                 RcppAnnoy_0.0.20           
[169] httr_1.4.4                  AnnotationDbi_1.60.0       
[171] sf_1.0-7                    ComplexHeatmap_2.15.1      
[173] colorspace_2.0-3            XML_3.99-0.13              
[175] tensor_1.5                  IRanges_2.32.0             
[177] splines_4.2.1               statmod_1.4.37             
[179] uwot_0.1.14                 spatstat.utils_3.0-1       
[181] scater_1.26.1               sp_1.5-1                   
[183] xgboost_1.6.0.1             plotly_4.10.1              
[185] xtable_1.8-4                jsonlite_1.8.4             
[187] R6_2.5.1                    pillar_1.8.1               
[189] htmltools_0.5.4             mime_0.12                  
[191] glue_1.6.2                  fastmap_1.1.0              
[193] BiocParallel_1.32.4         BiocNeighbors_1.16.0       
[195] class_7.3-20                codetools_0.2-18           
[197] utf8_1.2.2                  lattice_0.20-45            
[199] spatstat.sparse_3.0-0       tibble_3.1.8               
[201] curl_4.3.3                  ggbeeswarm_0.6.0           
[203] leiden_0.4.3                scDblFinder_1.12.0         
[205] limma_3.54.0                survival_3.4-0             
[207] repr_1.1.4                  munsell_0.5.0              
[209] e1071_1.7-12                GetoptLong_1.0.5           
[211] GenomeInfoDbData_1.2.9      iterators_1.0.14           
[213] reshape2_1.4.4              gtable_0.3.1               
[215] Seurat_4.3.0               
```

**Comment by zhanghao-njmu** [comment]
The old pip version may cause it.
You can upgrade pip with the following method:
 `SCP::check_Python(pkgs = "pip",envname = "SCP",force = T)` in R environment or in the shell with `path/to/SCP/bin/python -m pip install --upgrade pip`. 
Then reinstall the scipy.
If it does not work, you can also try to create the VirtualEnv with:
`PrepareVirtualEnv(pypi_mirror=pypi_mirror,remove_old=TRUE,install_python=TRUE)`

**Comment by zhanghao-njmu** [comment]
If the error "Object 'sys_bit' was not found" is reported. You can specify sys_bit variable by
`sys_bit <- ifelse(grepl("64", Sys.info()["machine"]), "64bit", "32bit")`
This is a bug in the SCP and I will fix it in the next version.

**Comment by hjh-air-cond** [comment]
Hi! 

I tried your suggestion! I think this may not be able to solve my problem, but if others have the same issue on Ubuntu Platform, your suggestion might be very useful!

The thing is that I try your suggestion many times as this:
```
[jinhang@c004 ~]$ ~/.virtualenvs/SCP/bin/python -m  pip install --upgrade pip
Requirement already satisfied: pip in ./.virtualenvs/SCP/lib/python3.8/site-packages (22.3.1)
[jinhang@c004 ~]$ ~/.virtualenvs/SCP/bin/python -m  pip install scipy
Requirement already satisfied: scipy in ./.virtualenvs/SCP/lib/python3.8/site-packages (1.9.3)
Requirement already satisfied: numpy<1.26.0,>=1.18.5 in ./.virtualenvs/SCP/lib/python3.8/site-packages (from scipy) (1.21.6)
[jinhang@c004 ~]$ ~/.virtualenvs/SCP/bin/python
Python 3.8.8 (default, Dec 13 2022, 00:50:51)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
Traceback (most recent call last):
  File "/home/jinhang/.virtualenvs/SCP/lib/python3.8/site-packages/scipy/__init__.py", line 166, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/jinhang/.virtualenvs/SCP/lib/python3.8/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "_ccallback_c.pyx", line 210, in init scipy._lib._ccallback_c
  File "/home/jinhang/.pyenv/versions/3.8.8/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jinhang/.virtualenvs/SCP/lib/python3.8/site-packages/scipy/__init__.py", line 171, in <module>
    raise ImportError(msg) from e
ImportError: The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.

```

Then I search found the error "ModuleNotFoundError: No module named '_ctypes'" seems caused by the CentOS platform doesn't have libffi-devel. Well, to me this problem can‘t be solved by now because I don't have the permission in our HPC to install libffi-devel by using yum.

So is there any possible ways to use a conda env for the RunSCVELO and RunPAGA function? Or could the PrepareVirtualEnv support creating envs with conda? Or any other solution you may suggest?

Thanks for all the help!
